var i18n = {
  current_language: 'es',
  js_about_thumbshot_thumbails: 'Acerca de Thumbshots thumbnails',
  js_add_note: 'Agregar Nota',
  js_admin: 'Administración',
  js_all: 'Todos',
  js_alphabetize: 'Alfabetizar',
  js_ambiguos_action: 'Acción Ambigüa.',
  js_an_error_occured: 'Ha ocurrido un error',
  js_apply_to_branch: 'Aplicar a Rama',
  js_april: 'Abril',
  js_april_short: 'Abr',
  js_are_you_sure: '¿Está seguro?',
  js_assigned_to: 'Asignado a:',
  js_attachments: 'Archivos adjuntos',
  js_august: 'Agosto',
  js_august_short: 'Ago',
  js_browse_icon_library: 'Explorar libreria de Íconos...',
  js_browse_image_library: 'Explorar librería...',
  js_browser_not_supported: 'Navegador no soportado',
  js_c_to_copy_content_to_clipboard: '-C para copiar el contenido a su portapapeles',
  js_cancel: 'Cancelar',
  js_cancel_invitations_warning: 'Las invitaciones no serán enviadas - por favor confirme.',
  js_cant_cache_every_file: 'Hubo un problema de almacenamiento en caché los archivos para el modo sin conexión. Lo sentimos mucho y estamos tratando de solucionar el problema tan pronto como sea posible. ¿Quiere conectarse ahora?',
  js_cant_copy_into_self_or_children: 'No se puede copiar en hijo o en si mismo!',
  js_cant_delete_root_note: '¡El nodo raiz no puede borrarse!',
  js_cant_go_online_we_are_sorry_force_online: 'Hubo un error con los cambios que hizo. Lo sentimos mucho y trataremos de corregir esto lo mas pronto posible ¿Desea forzar el modo con conexión?',
  js_cant_move_root_note: 'No puede borrar el nodo raiz.',
  js_cant_paste_in_same_tree: 'No puede pegar en el mismo arbol.',
  js_certain_features_may_not_be_available: 'Algunas caracteristicas podrian no estar disponibles',
  js_check_out_this_map: 'Revisar este mapa mental MindMeister:',
  js_clear_color: 'Clear Color',
  js_click_to_filter_by_this_idea: 'Haga clic para filtrar los cambios por esta idea',
  js_click_to_filter_by_this_user: 'haga clíc para filtrar los cambios por este usuario',
  js_clone: 'Clonar',
  js_clone_public_map: 'Clonar mapa público',
  js_cloned_revision: 'La revisión actual se ha guardado como un nuevo mapa mental en su lista de mapas.',
  js_close: 'Cerrar',
  js_color: 'Color',
  js_complete: 'Completo',
  js_confirm_leave_page: 'Algunos cambios no han sido guardados en el servidor.',
  js_conflict_detected_on: 'Conflicto detectado en',
  js_connect_node_to_itself: 'No puede conectarse un nodo consigomismo.',
  js_connection_color: 'Color de Conexión',
  js_connection_delete: 'Eliminar conexión',
  js_connection_to_server_lost: '¡Se ha perdido la conexión con el servidor!',
  js_copied_to_clipboard: 'Copiado al portapapeles',
  js_copy: 'Copiar',
  js_copy_as_text: 'Copiar como texto',
  js_copy_link: 'Copiar Enlace',
  js_create_as_map: 'Crear como Mapa',
  js_create_as_map_add_back_link: 'Add link back to this map',
  js_create_as_map_add_link: 'Añadir vínculo al nuevo mapa',
  js_create_as_map_explanation: 'Esto creara un nuevo mapa para la idea seleccionada y todas las ideas hijo serán movidas al nuevo mapa.',
  js_create_as_map_preserve_permissions: 'Preservar permisos de compartir',
  js_critical_error_occured: 'Un error critico ha ocurrido en MindMeister.',
  js_cut: 'Cortar',
  js_december: 'Diciembre',
  js_december_short: 'Dic',
  js_delete: 'Borrar',
  js_delete_folder: 'Borrar Carpeta',
  js_delete_folder_warning: 'Todos los contenidos de esta carpeta se eliminarán.',
  js_delete_folders_warning: 'Todos los contenidos de las carpetas serán eliminados',
  js_delete_items: 'Eliminar elementos',
  js_delete_mind_map: 'Borra Mapa Mental',
  js_details: 'Detalles',
  js_did_you_know: '¿Sabia que...',
  js_direct_link: 'Vínculo Directo',
  js_disable_account: 'Deshabilitar',
  js_discard_changes: 'Descartar cambios',
  js_do_you_want_to_clone_map_to_account: '¿quiere copiar este mapa a su cuenta?',
  js_do_you_want_to_continue: '¿Desea continuar?',
  js_done_lower: 'Hecho',
  js_due_date: 'Fecha de Vencimiento:',
  js_duplicate: 'Duplicar',
  js_duplicating: 'Duplicando ...',
  js_duration: 'Duración',
  js_edit: 'Editar',
  js_edit_caption: 'Editar Subtitulo',
  js_edit_folder: 'Editar Carpeta',
  js_edit_label: 'Editar etiqueta',
  js_edit_map_theme: 'Personalizar plantilla del mapa ...',
  js_edit_note: 'Editar Nota',
  js_email_invalid: 'Escriba una dirección válida de correo electrónico ',
  js_email_link: 'Vínculo al Email',
  js_emptying_trashcan: 'Vaciando la papelera ...',
  js_enable_account: 'Habilitar',
  js_entering_brainstorming_mode: 'Entrando en Modo Lluvia de Ideas',
  js_error: 'Error',
  js_error_caching_files: 'Error de ficheros de caché',
  js_error_commiting_offline_changes: 'Error en los cambios sin conexión',
  js_error_encountered_when_putting_maps_online: 'Se encontro un error al regresar los mapas a modo con conexión.',
  js_error_encountered_when_taking_maps_offline: 'Se encontro un error al llevar los mapas a modo sin conexión',
  js_errors_occured_while_getting_changes: 'Ocurrieron errores al obtener los cambios del servidor.',
  js_event_logged_and_error_will_be_corected: 'Lamentamos las inconveniencias, el evento ha sido registrado y el error sera corregido tán pronto sea posible.',
  js_export: 'Exportar',
  js_external_link: 'Vinculo externo',
  js_external_save_failed: 'No se pudieron guardar los cambios a su mapa',
  js_external_save_successful: '¡Los cambios a su mapa se guardaron con éxito!',
  js_february: 'Febrero',
  js_february_short: 'Feb',
  js_file_successfully_imported: 'File successfully imported',
  js_filter_all: 'Todo',
  js_filter_author: 'Editar usuario',
  js_filter_icons: 'Icon',
  js_filter_idea: 'Título de la idea',
  js_filter_task: 'Propietario de la tarea',
  js_filter_topics: 'Filter topics',
  js_font_size: 'Tamaño de Fuente',
  js_font_style: 'Estilo de Fuente',
  js_friday: 'Viernes',
  js_friday_short: 'Vie',
  js_getting_auto_link: 'obteniendo WunderLink',
  js_google_cannot_be_contacted: 'Está trabajando en modo sin conexión. Google no puede ser contactado.',
  js_google_could_not_be_contacted: 'No se pudo contactar con google. por favor intentelo más tarde.',
  js_group_chat: 'Grupo de chat',
  js_help: 'Ayuda',
  js_helper_days: 'días',
  js_helper_hours: 'horas',
  js_helper_months: 'meses',
  js_helper_weeks: 'semanas',
  js_history_added_attachment_to: 'añadió un archivo adjunto a<i>%s</i>',
  js_history_added_connection: 'añadió una conexión de <I>%s</i> a <I>%s</i>',
  js_history_added_icon_to: 'añadió un ícono a <i>%s</i>',
  js_history_added_image_to_s: 'agregó una imagen a <em class="change">%s</em>',
  js_history_added_link_to: 'añadió un vínculo a <i>%s</i>',
  js_history_added_note_to: 'añadió una nota a <i>%s</i>',
  js_history_added_task_to: 'añadió una tarea a<i>%s</i>',
  js_history_added_text_style_to: 'añadió un estilo de texto a <i>%s</i>',
  js_history_changed_an_icon_s: 'icono cambiado en <em class="change">%s</em>',
  js_history_changed_connection_color: 'conexión de colores cambiado de %s a %s',
  js_history_created_the_map: ' creó un mapa',
  js_history_edited_link_on: 'vínculo editado en <i>%s</i>',
  js_history_edited_map_theme: 'plantilla de mapa cambiada',
  js_history_edited_note_on: 'nota editada en %s',
  js_history_edited_task_on: 'editó la tarea en <i>%s</i>',
  js_history_inserted: 'insertado <i>%s</i>',
  js_history_moved: 'movido %s',
  js_history_removed: 'eliminado <i>%s</i>',
  js_history_removed_attachment_from: 'eliminó un archivo adjunto de <i>%s</i>',
  js_history_removed_connection: 'eliminó la conexión de <I>%s</i> a <I>%s</i>',
  js_history_removed_icon_from: 'eliminar un icono desde <i>%s</i>',
  js_history_removed_image_from_s: 'imagen eliminada de <em class="change">%s</em>',
  js_history_removed_link_from: 'eliminó vínculo desde <i>%s</i>',
  js_history_removed_note_from: ' eliminó una nota de <i>%s</i>',
  js_history_removed_task_from: 'eliminó una tarea de <i>%s</i>',
  js_history_renamed: 'renombrado de <i>%s</i> a <i>%s</i>',
  js_history_repositioned: 'reposicionado <i>%s</i>',
  js_history_resized_image_on_s: 'imagen redimensionada en <i>%s</i>',
  js_history_set_a_task_to_completed_d_s: 'establecer la tarea <i>%s</i> a %s completada',
  js_history_set_the_priority_of_a_task_to_s_s: 'establecer la prioridad de <i>%s</i> a %s',
  js_iconfinder_could_not_be_contacted: 'Icono del Finder no pudo ser contactado. Por favor, inténtelo de nuevo más tarde.',
  js_icons_s: '%s íconos',
  js_image_could_not_be_found: 'No se encontro la imagen',
  js_image_does_not_match: 'La imagen no coincide',
  js_image_not_available: 'Imagen no disponible',
  js_image_too_big: 'This map exceeds the recommended maximum size for image export. Please consider exporting to PDF instead',
  js_image_unavailable: 'Imagen no disponible',
  js_images_d: '%d imagenes',
  js_images_s: '%s imágenes',
  js_import_error: 'Some error(s) occurred on importing',
  js_in_this_map: 'en este mapa',
  js_inaccessible_map: 'Mpa Inaccesible',
  js_info: 'Información',
  js_invalid_attachment: 'Archivo inválido',
  js_invalid_attachment_will_be_removed: 'este archivo no es valido(excede el tamaño), fue removido de su nodo. Porfavor intentelo otra vez con otro archivo.',
  js_invalid_image: 'Imagen no válida',
  js_invalid_link: 'Vínculo invalido:',
  js_invalid_task_date: 'Fecha de vencimiento invalida para esta tarea. Porfavor introduzca una fecha valida para esta tarea',
  js_invite_people: 'Invitar Personas',
  js_items_s: '(%s items)',
  js_january: 'Enero',
  js_january_short: 'Ene',
  js_july: 'Julio',
  js_july_short: 'Jul',
  js_june: 'Junio',
  js_june_short: 'Jun',
  js_keep: 'Mantener',
  js_keepaligned: 'Mantener alineado',
  js_learn_more: 'Más información',
  js_link_to_topic: 'Vínculo al tema',
  js_links: 'Vínculo',
  js_loading_image: 'Carga de imagen',
  js_loading_template: 'Creating map from template...',
  js_login_failed_try_again_later_to_go_online: 'Login on MindMeister failed. Please try to go online again or try again later.',
  js_make_admin: 'Convertir en administrador',
  js_make_normal_member: 'Retirar de administradores',
  js_map_info: 'Información',
  js_map_modified_online_please_choose_action: 'El mapa ha sido modificado en el servidor mientras estuvo sin conexión. Porfavor elija una de las opciones de abajo.',
  js_map_not_share_with_u_anymore_contact_s: 'Este mapa ya no se comparte con usted. Porfavor contacte al dueño %s y pidale que lo comparta con usted nuevamente.',
  js_map_saved: 'Mapa guardado...',
  js_march: 'Marzo',
  js_march_short: 'Mar',
  js_maximum_zoomlevel_reached: 'se ha alcanzado el nivel máximo de acercamiento.',
  js_may: 'Mayo',
  js_me: 'Yo',
  js_mindmeister_default: 'Predeterminadas de Mindmeister',
  js_minimum_zoomlevel_reached: 'se ha alcanzado el nivel minimo de acercamiento.',
  js_modified_by_s_s: 'Modificado por %s en %s',
  js_monday: 'Lunes',
  js_monday_short: 'Lun',
  js_month: 'mes',
  js_more_child_ideas_d: '%d Ideas Hijo',
  js_must_cut_something_first: 'Debe cortar algo primero.',
  js_must_select_destination: 'Debe eljir un destino.',
  js_must_select_something_first: 'Debe seleccionar algo primero.',
  js_myaccount: 'Mi Cuenta',
  js_myteam: 'Mi Equipo',
  js_name: 'Nombre',
  js_network_error: 'Error en la red',
  js_new_folder: 'Nueva Carpeta',
  js_new_node: 'Nuevo nodo',
  js_no: 'No',
  js_no_attachments: 'No hay archivos adjuntos',
  js_no_auto_image_was_found: 'No se encontro un WunderBild par el tema',
  js_no_auto_note_found_for_topic: 'No se encontró WunderNote para el tema',
  js_no_border_set: 'El nodo seleccionado no tiene bordes. Por favor, elija un tema que haya contenido bordes anteriormente.',
  js_no_default_images: 'No hay imagenes predeterminadas',
  js_no_guarantee_of_losing_changes_retry_first: 'No podemos garantizar que los cambios sin conexión no se pierdan (así que quizás quiera presionar No y reintentar activar caché de los archivos para el modo fuera de línea)',
  js_no_icon_selected: 'Usted tiene que seleccionar un icono primero',
  js_no_image_selected: 'Debe seleccionar una imagen primero',
  js_no_image_was_found: 'No hay imágenes - por favor trate de acortar los términos de búsqueda',
  js_no_images: 'No hay imagenes',
  js_no_internet_connection_available_now: 'Esta acción requiere conexión a internet y no hay una conexión disponibloe en este momento',
  js_no_link_found_for_topic: 'No se encontro WunderLink para el tema',
  js_no_matches_found: 'No se han encontrado coincidencias',
  js_no_permissions_to_perform_this_action: 'Usted no está autorizado para realizar esta acción.',
  js_no_results_received: 'No se encontraron resultados',
  js_node_copied_unavailable: 'El nodo que copió ya no está disponible',
  js_node_cut_unavailable: 'El nodo que cortó ya no está disponible',
  js_node_has_no_image: 'El nodo seleccionado no tiene imagen',
  js_none: 'Ninguno',
  js_none_is_editing_on_this_map_now: 'Nadie mas esta editando este mapa mental',
  js_not_started: 'no iniciado',
  js_note: 'Nota',
  js_note_is_too_long: 'La nota es demasiado larga',
  js_notes: 'Notas',
  js_notice: 'Aviso',
  js_november: 'Noviembre',
  js_november_short: 'Nov',
  js_numbering: 'Número',
  js_numbering_clear: 'Remove numbering',
  js_numbering_heading: 'Numbering',
  js_numbering_hint: 'It seems that the child nodes are already numbered.',
  js_numbering_renumber: 'Renumber',
  js_october: 'Octubre',
  js_october_short: 'Oct',
  js_offline: 'Fuera de línea',
  js_offline_cannot_upload_attachments: 'Attachment Upload is not supported offline',
  js_offline_feature_unavailable_on_this_browser: 'Su Navegador aún no soporta esta característica.',
  js_offline_mode: 'Modo Fuera de Linea',
  js_offline_word: 'fuera de línea',
  js_ok: 'OK',
  js_older_messages: 'Mostrar mensajes anteriores',
  js_one_child_idea: 'Una Idea Hijo',
  js_one_level: 'Un Nivel',
  js_online: 'En línea',
  js_open: 'Abrir',
  js_open_source_page: 'Ver en la página de origen',
  js_other_users_editing: '- Otros usuarios estan editando ahora',
  js_overdue: 'Atrasado',
  js_override: 'Sobreescribir',
  js_override_theme: 'Estilos personalizados encontrados',
  js_override_theme_text: 'En este mapa, los estilos por defecto del tema en algunos nodos fueron modificados. Deseas guardar tus estilos personalizados o sobreescribirlos con los del nuevo tema?',
  js_paste: 'Pegar',
  js_people: 'people',
  js_person: 'person',
  js_please_note_browser_not_supported_link: 'Tenga en cuenta que su explorador no es compatible con MindMeister. Vea la %slista de navegadores compatibles%s.',
  js_please_select_an_idea_first: 'Porfavor elija una idea primero',
  js_please_select_something_first: 'Por favor, seleccione un elemento en la primera lista, haciendo clic en la fila respectiva',
  js_please_wait_for_attachments_synchronization: 'Por favor espere a que se suban los archivos adjuntos',
  js_please_wait_for_caching_files: 'Actualizando el cache fuera de linea',
  js_please_wait_for_map_synchronization: 'Por favor espera que el mapa se sincronize',
  js_please_wait_while_we_save_to_google_docs: 'Por favor espera mientras guardamos tu mapa en Google Docs...',
  js_present: 'Start Presentation',
  js_press_ok_to_reload_page: 'Porfavor presione Ok para actualizar la pagina.',
  js_print: 'Imprimir',
  js_priority: 'Prioridad',
  js_priority_s: 'Prioridad %s',
  js_properties: 'Propiedades',
  js_public_map: 'PÚBLICO',
  js_publish: 'Publicar',
  js_remove: 'Quitar',
  js_remove_attachment: 'Quitar archivo adjunto',
  js_remove_icon: 'Quitar Ícono',
  js_removing_collaborator: 'Removiendo a Colaborador',
  js_report_abuse: 'Reportar Abuso',
  js_retrying_in_seconds: 'volver a intentar en 10 segundos.',
  js_revert_to_revision_warning: 'Todos los cambios desde la revisión %s se perderán irreversiblemente. ¿Seguro que desea continuar?',
  js_s_still_has_tasks_sure_want_to_remove_s: '%s aun tiene tareas asignadas en este mapa mental. Está seguro de que desea remover a %s de su lista para compartir?',
  js_saturday: 'Sabado',
  js_saturday_short: 'Sab',
  js_save_as_new_map: 'Guardad como nuevo mapa',
  js_saving: 'Guardando...',
  js_scrollbars: 'Scrollbars',
  js_search: 'Buscar',
  js_september: 'Septiembre',
  js_september_short: 'Sep',
  js_settings: 'Configuración ...',
  js_share: 'Compartir',
  js_show_detail: 'Mostrar Detalle',
  js_signout: 'Desconectar',
  js_split: 'Split into Nodes',
  js_start_date: 'Fecha de Inicio:',
  js_start_date_is_set_after_due_date: 'La fecha de inicio es posterior a la fecha de vencimiento',
  js_status_idle: 'Estado: reposo',
  js_status_updating_changes_from_server: 'Estado: actualizando cambios desde el servidor',
  js_sunday: 'Domingo',
  js_sunday_short: 'Dom',
  js_taking_s_maps_offline_s: 'Tomando %s mapas',
  js_task_information: 'Información de Tarea',
  js_tasks: 'Tareas',
  js_text_outline: 'bosquejo del texto',
  js_the_following_attachments_failed: 'Los siguientes archivos no pudieron adjuntarse:',
  js_theme: 'Plantilla',
  js_there_are_no_revisions_for_this_map_it_was_not_modified_yet: 'No hay revisiones para este mapa. Lo mas probable es que aún no ha sido modificado.',
  js_there_are_no_suggestions: 'No hay sugerencias. Por favor intente otra búsqueda.',
  js_this_image_may_be_subject_to_copyright: 'Esta imagen puede estar sujeta a derechos de autor',
  js_this_map_cant_be_initialized: 'Este mapa no puede inicializarse',
  js_thursday: 'Jueves',
  js_thursday_short: 'Jue',
  js_tools: 'Herramientas',
  js_topic: 'Tema',
  js_translate: 'Traducir',
  js_trashcan_warning: '¿Estas seguro que quieres vaciar tu papelera? Esta operación no se puede recuperar y sus mapas se eliminarán para siempre.',
  js_tuesday: 'Martes',
  js_tuesday_short: 'Mar',
  js_two_levels: 'Dos Niveles',
  js_undelete: 'Recuperar',
  js_unsupported_file_type: 'Tipo de archivo no permitido',
  js_upgrade: 'Actualización',
  js_upload_new_image: 'Subir una imagen...',
  js_use_an_image_from_the_web: 'Usar imagen de web...',
  js_use_new_browser_for_offline_mode: 'El modo fuera de línea de MindMeister utiliza las características avanzadas de HTML5 que están disponibles solamente en Google Chrome y Safari. Firefox e Internet Explorer serán compatibles tan pronto como HTML5 sea suficientemente soportado.',
  js_view_changes_on_this_idea: 'Ver Cambios...',
  js_view_only_map: 'SÓLO VISTA',
  js_warning: 'Advertencia',
  js_we_are_sorry_request_was_not_done: 'Lo sentimos, pero su petición no pudo completarse. Ocurrió un error. Porfavor intentelo otra vez.',
  js_wednesday: 'Miércoles',
  js_wednesday_short: 'Mie',
  js_what_to_do: 'What do you want to do?',
  js_wrong_password_please_try_again: 'Password incorrecto - por favor intente denuevo ',
  js_year: 'año',
  js_yes: 'SI',
  js_you_are_about_to_delete: 'Está a punto de borrar',
  js_you_are_about_to_delete_items_s: 'Está a punto de borrar los siguientes items: %s',
  js_you_are_about_to_withdraw: 'Esta apunto de retirarse de un mapa',
  js_you_are_in_view_only_mode: 'Esta en modo solo lectura',
  js_you_are_not_connected_to_internet_connect_and_try_again: 'no está conectado a internet. Please connect and try again.',
  js_you_are_working_offline_now_can_edit_and_create_new_maps: 'Esta trabajando sin conexión ahora. Puede editar todos los mapas disponibles asi como crear nuevos mapas.',
  js_you_can_undo_afterwards: 'Despuñes podrás deshacer todos los cambios.',
  js_you_cannot_use_undo_redo_in_collaborative_mode: 'Por favor salga del modo lluvia de ideas pidiendo a sus colaboradores que cierren el mapa para poder deshacer los cambios de manera segura.',
  js_you_cant_do_that_now: 'Lo sentimos, no puede hacer eso ahora.',
  js_you_cant_do_things_become_premium_to_do_that_s: '<em>Lo sentimos, %s es para cuentas pagas únicamente </em>Actualice su cuenta a %s.',
  js_you_still_have_tasks_sure_want_to_withdraw: 'Aun tiene tareas asignadas en este mapa. ¿Esta seguro que deses retirarse?',
  js_you_will_loose_all_press_no_end_export_first: 'Perderá todos los cambios hechos fuera de línea. Recomendamos copiar el código de los cambios que aparece a continuación y enviarlo a support@mindmeister.com para recuperar los cambios no guardados.',
  js_your_request_was_not_done: 'Petición fallida'
}